services:
  astro:
    security_opt: ["seccomp=unconfined"]
    build:
      context: .
      dockerfile: Containerfile
      shm_size: "1gb"
    init: true
    command:
      [
        "sh",
        "-c",
        "rm -f .astro/dev.json && exec node_modules/.bin/astro dev --host 0.0.0.0",
      ]
    ports:
      - target: 4321
        published: "4321"
    volumes:
      - ./:/website:z
      - /website/app/node_modules
