#!/usr/bin/env bash
#
# gen-git-env.sh — generate git.env for the dev container from the host's own
# git identity and gh token. Run on the HOST, from the repo root (or anywhere
# inside it). Re-run whenever the token rotates (gh auth refresh).
#
# Wire-up: compose reads it via `env_file: git.env` on the service (or rename
# to plain `.env` for automatic pickup). Keep it out of git either way.

set -euo pipefail

OUT=".env"

name="$(git config user.name)"   || { echo "error: git user.name not set on host" >&2; exit 1; }
email="$(git config user.email)" || { echo "error: git user.email not set on host" >&2; exit 1; }
token="$(gh auth token)"         || { echo "error: gh not authenticated (run: gh auth login)" >&2; exit 1; }

umask 177   # 0600: the token is a secret; nobody else reads this file

cat > "$OUT" <<EOF
# GENERATED by gen-git-env.sh — do not edit, do not commit. Regenerate after
# 'gh auth refresh'. Consumed by compose (env_file / .env).
GH_TOKEN=$token
GIT_NAME=$name
GIT_EMAIL=$email
GIT_AUTHOR_NAME=$name
GIT_AUTHOR_EMAIL=$email
GIT_COMMITTER_NAME=$name
GIT_COMMITTER_EMAIL=$email
EOF

# Ensure env files can never be committed: append '*.env' to the repo-root
# .gitignore unless a covering pattern is already present.
root="$(git rev-parse --show-toplevel)"
if ! grep -qxE '\*?\.env|\*\.env' "$root/.gitignore" 2>/dev/null; then
  printf '\n# env files carry secrets (gen-git-env.sh): never committed\n*.env\n' >> "$root/.gitignore"
  echo "added '*.env' to $root/.gitignore"
fi

echo "wrote $OUT (mode 0600) for $name <$email>"
