// Astro integration: writes dist/_headers at build time with a CSP whose
// inline-script hashes are computed from the actual built HTML — so they can
// never drift from what ships. Edit the policy/headers here; the hashes fill in
// automatically. (Bundled component scripts are external via
// vite.build.assetsInlineLimit:0, so only hand-written is:inline scripts —
// and any inline JSON-LD — get hashed.)
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

// script-src is appended with 'self' + the discovered inline hashes.
const DIRECTIVES = [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "connect-src 'self'",
];

const EXTRA_HEADERS = [
    "X-Content-Type-Options: nosniff",
    "Referrer-Policy: strict-origin-when-cross-origin",
    "Permissions-Policy: accelerometer=(), autoplay=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=(), browsing-topics=()",
    "X-Frame-Options: DENY",
    "Strict-Transport-Security: max-age=31536000; includeSubDomains",
];

// Inline <script> = no src attribute. `</script>` can't appear literally inside
// one per the HTML spec, so the non-greedy match is safe.
const SCRIPT_RE = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;

export default function cspHeaders() {
    return {
        name: "csp-headers",
        hooks: {
            "astro:build:done": ({ dir, logger }) => {
                const dist = fileURLToPath(dir);
                const pages = readdirSync(dist, { recursive: true }).filter(
                    (f) => typeof f === "string" && f.endsWith(".html"),
                );

                const hashes = new Set();
                for (const page of pages) {
                    const html = readFileSync(join(dist, page), "utf8");
                    for (const [, attrs, body] of html.matchAll(SCRIPT_RE)) {
                        if (/\bsrc\s*=/i.test(attrs)) continue; // external → 'self'
                        const digest = createHash("sha256")
                            .update(body, "utf8")
                            .digest("base64");
                        hashes.add(`'sha256-${digest}'`);
                    }
                }

                const csp = [
                    ...DIRECTIVES,
                    `script-src 'self' ${[...hashes].sort().join(" ")}`,
                ].join("; ");

                const out =
                    [
                        "# GENERATED by csp-headers.mjs on `astro build` — do not edit by hand.",
                        "# Change the policy or headers in csp-headers.mjs instead.",
                        "/*",
                        `  Content-Security-Policy: ${csp}`,
                        ...EXTRA_HEADERS.map((h) => `  ${h}`),
                    ].join("\n") + "\n";

                writeFileSync(join(dist, "_headers"), out);
                logger.info(
                    `_headers written (${hashes.size} inline-script hash${
                        hashes.size === 1 ? "" : "es"
                    })`,
                );
            },
        },
    };
}
